### PR TITLE
Fixes/results docstrings

### PR DESCRIPTION
**Pull request by henhuy**
Refactors python code in docstrings into code blocks, which are not tested in doctests.

Once #39 is merged, this can be merged.

### CODE REVIEW

**Comment by henhuy** [comment]
Don't see why travis fails...?!

**Review by uvchik — COMMENTED** [review]
You have inherited some failing tests from my PR. I merged the dev-branch to fix them.

I think the docs are cleaner now, but there are still no tests.

**Comment by henhuy** [comment]
Hey @uvchik,
how should I test against a DB? 
Mock it or can I set one up using tox?

**Review by uvchik — APPROVED** [review]
In my opinion we should merge this PR, because it is fine and open an issue to add more tests.

**Pull request merged**
